### PR TITLE
footer-added

### PR DESCRIPTION
**Pull request by ratishjain12**
Added a footer :)

### CODE REVIEW

**Comment by Aryainguz** [comment]
Hey @ratishjain12 the PR is having conflicts as another contribution has been made after your forked so please make another PR after syncing up the project

**Comment by ratishjain12** [comment]
> Hey @ratishjain12 the PR is having conflicts as another contribution has been made after you forked so please make another PR after syncing up the project

Yeah one sec

**Comment by Aryainguz** [comment]
Great job @ratishjain12 👏

**Comment by ratishjain12** [comment]
Hey bro is there a swoc label for it to count under swoc? If yes please add it

**Pull request merged**
